# Generated by Django 4.0.5 on 2022-06-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
