# Generated by Django 4.0.5 on 2022-06-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_order_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_address',
            field=models.CharField(max_length=255),
        ),
    ]
