# Generated by Django 4.0.5 on 2022-06-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('service', '0006_alter_order_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='restaraunt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.restaraunt', verbose_name='Restaraunt'),
        ),
    ]
