# Generated by Django 4.0.5 on 2022-06-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_order_options_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='hidden',
        ),
        migrations.AddField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
