# Generated by Django 4.0.5 on 2022-06-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_remove_review_hidden_review_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_phone',
            field=models.CharField(default='', max_length=12, verbose_name='Телефон'),
        ),
    ]
