# Generated by Django 4.0.5 on 2022-06-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_order_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
    ]
