# Generated by Django 4.0.5 on 2022-06-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_order_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client_phone',
            field=models.CharField(default='', max_length=12, verbose_name='Телефон'),
        ),
    ]
