# Generated by Django 4.0.5 on 2022-06-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_dish_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='portion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
