# Generated by Django 4.0.5 on 2022-06-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_portion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name_ru'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'ordering': ['name_ru'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
