# Generated by Django 4.0.5 on 2022-06-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('position_ru', models.CharField(max_length=50)),
                ('position_en', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='nuretaneko/media/employees')),
                ('description_ru', models.CharField(max_length=255)),
                ('description_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='nuretaneko/media/news')),
                ('text_ru', models.TextField()),
                ('text_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('address_ru', models.CharField(max_length=100)),
                ('address_en', models.CharField(max_length=100)),
                ('description_ru', models.CharField(max_length=255)),
                ('description_en', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='nuretaneko/media/restaraunts')),
            ],
        ),
    ]
