# Generated by Django 4.0.5 on 2022-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name_ru'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['title_ru'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='restaraunt',
            options={'ordering': ['name_ru'], 'verbose_name': 'Ресторан', 'verbose_name_plural': 'Рестораны'},
        ),
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время добавления'),
        ),
        migrations.AddField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время добавления'),
        ),
        migrations.AddField(
            model_name='restaraunt',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='restaraunt',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description_ru',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='nuretaneko/media/employees', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_ru',
            field=models.CharField(max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='nuretaneko/media/news', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_ru',
            field=models.TextField(verbose_name='Текст объявления'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='restaraunt',
            name='address_ru',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='restaraunt',
            name='description_ru',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='restaraunt',
            name='name_ru',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='restaraunt',
            name='photo',
            field=models.ImageField(upload_to='nuretaneko/media/restaraunts', verbose_name='Фото'),
        ),
    ]
