# Generated by Django 4.0.5 on 2022-06-18 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Название')),
                ('name_en', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], max_length=20, verbose_name='Статус')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100)),
                ('description_ru', models.CharField(max_length=255)),
                ('description_en', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость')),
                ('photo', models.ImageField(upload_to='nuretaneko/media/dishes')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('portion', models.PositiveIntegerField(default=0, verbose_name='Порция')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.dishcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['name_ru'],
            },
        ),
    ]
